# Phase 4: Machine Learning Model Development

## Objective

The objective of this phase is to train multiple supervised machine learning models for predicting cardiovascular disease using the preprocessed clinical dataset.

The processed training and testing datasets prepared during the preprocessing phase are used directly to avoid repeating data preparation steps. Each model is trained independently, and prediction results are generated for evaluation in the next phase.

---

## Machine Learning Models

- Logistic Regression
- Decision Tree
- Random Forest
- Support Vector Machine (SVM)
- K-Nearest Neighbors (KNN)
- XGBoost

In [5]:
# ==========================================================
# Step 1: Import Required Libraries
# ==========================================================

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import joblib

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score

from xgboost import XGBClassifier

In [6]:
# ==========================================================
# Step 2: Load Processed Datasets
# ==========================================================

X_train = pd.read_csv("../data/processed/X_train_scaled.csv")
X_test = pd.read_csv("../data/processed/X_test_scaled.csv")

y_train = pd.read_csv("../data/processed/y_train.csv").squeeze()
y_test = pd.read_csv("../data/processed/y_test.csv").squeeze()

print("Training Features :", X_train.shape)
print("Testing Features :", X_test.shape)

print("Training Labels :", y_train.shape)
print("Testing Labels :", y_test.shape)

Training Features : (54564, 12)
Testing Features : (13641, 12)
Training Labels : (54564,)
Testing Labels : (13641,)


In [ ]:
# ==========================================================
# Step 3: Verify Dataset Shapes
# ==========================================================

X_train.head()
X_train.describe()

,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,age_years,bmi
count,54564.000000,5.456400e+04,5.456400e+04,5.456400e+04,5.456400e+04,54564.000000,54564.000000,54564.000000,54564.000000,54564.000000,5.456400e+04,5.456400e+04
mean,1.348197,1.471638e-15,5.202365e-16,1.198041e-17,-1.647307e-16,1.364838,1.225918,0.086596,0.052489,0.804175,4.523909e-16,-8.112824e-16
std,0.476403,1.000009e+00,1.000009e+00,1.000009e+00,1.000009e+00,0.679491,0.571967,0.281244,0.223013,0.396838,1.000009e+00,1.000009e+00
min,1.000000,-1.341858e+01,-3.713053e+00,-2.277883e+00,-2.323496e+00,1.000000,1.000000,0.000000,0.000000,0.000000,-3.529162e+00,-3.280912e+00
25%,1.000000,-6.586825e-01,-6.368401e-01,-4.040255e-01,-1.387602e-01,1.000000,1.000000,0.000000,0.000000,1.000000,-7.185161e-01,-6.116559e-01
50%,1.000000,7.746573e-02,-1.474426e-01,-4.040255e-01,-1.387602e-01,1.000000,1.000000,0.000000,0.000000,1.000000,2.112764e-02,-2.014256e-01
75%,2.000000,6.909226e-01,5.516967e-01,8.452129e-01,9.536076e-01,1.000000,1.000000,0.000000,0.000000,1.000000,7.607714e-01,4.378487e-01
max,2.000000,5.230503e+00,8.801540e+00,3.343690e+00,4.230711e+00,3.000000,3.000000,1.000000,1.000000,1.000000,1.648344e+00,4.214307e+01


## Observation

The processed datasets were successfully loaded and verified.

### Key Findings

- Both scaled and unscaled datasets are available.
- The training and testing datasets contain consistent features.
- The data is ready for machine learning model development.

In [7]:
# ==========================================================
# Step 4: Train Logistic Regression
# ==========================================================

logistic_model = LogisticRegression(
    random_state=42,
    max_iter=1000
)

logistic_model.fit(X_train, y_train)

print("Logistic Regression Model Trained Successfully.")

Logistic Regression Model Trained Successfully.


In [ ]:
# ==========================================================
# Step 5: Logistic Regression Predictions
# ==========================================================

y_pred_lr = logistic_model.predict(X_test)

## Observation

The Logistic Regression model was successfully trained using the scaled training dataset. Predictions were generated for the testing dataset and will be evaluated in the next phase.

In [9]:
# ==========================================================
# Step 6: Logistic Regression Accuracy
# ==========================================================

lr_accuracy = accuracy_score(y_test, y_pred_lr)

print(f"Accuracy : {lr_accuracy:.4f}")

Accuracy : 0.7298


## Observation

Evaluate the prediction accuracy of the Logistic Regression model using the testing dataset.

In [10]:
# ==========================================================
# Step 7: Saving Logistic Regression Model
# ==========================================================

joblib.dump(
    logistic_model,
    "../models/logistic_regression.pkl"
)

print("Logistic Regression Model Saved Successfully.")

Logistic Regression Model Saved Successfully.


In [11]:
# ==========================================================
# Step 8: Train Decision Tree Model
# ==========================================================

decision_tree = DecisionTreeClassifier(
    random_state=42
)

decision_tree.fit(X_train, y_train)

print("Decision Tree Model Trained Successfully.")

Decision Tree Model Trained Successfully.


In [12]:
# ==========================================================
# Step 9: Decision Tree Predictions
# ==========================================================

y_pred_dt = decision_tree.predict(X_test)

## Observation

The Decision Tree model was successfully trained using the unscaled training dataset.

These predictions will be evaluated and compared with other machine learning models in the next phase to determine the model's overall performance.

In [14]:
# ==========================================================
# Step 10: Decision Tree Accuracy
# ==========================================================

dt_accuracy = accuracy_score(y_test, y_pred_dt)

print(f"Accuracy : {dt_accuracy:.4f}")

Accuracy : 0.6417


In [15]:
# ==========================================================
# Step 11: Saving Decison Tree Model
# ==========================================================

joblib.dump(
    decision_tree,
    "../models/decision_tree.pkl"
)

print("Decision Tree Model Saved Successfully.")

Decision Tree Model Saved Successfully.


In [13]:
# ==========================================================
# Step 8: Train Random Forest Model
# ==========================================================

# Initialize Random Forest Classifier
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train the model
rf_model.fit(X_train, y_train)

print("Random Forest model trained successfully.")

Random Forest model trained successfully.


In [14]:
# ==========================================================
# Step 9: Random Forest Predictions
# ==========================================================

# Generate predictions
y_pred_rf = rf_model.predict(X_test)

# Display first 10 predictions
print("First 10 Predictions:")
print(y_pred_rf[:10])

First 10 Predictions:
[0 1 1 1 1 0 0 1 0 0]


## Observation

The Random Forest model was successfully trained using the unscaled training dataset.

The model generated predictions for the testing dataset. Random Forest combines multiple decision trees to improve prediction accuracy and reduce overfitting compared to a single Decision Tree. The generated predictions will be evaluated in the next phase.

In [15]:
# ==========================================================
# Step 10: Train Support Vector Machine (SVM)
# ==========================================================

# Initialize SVM Classifier
svm_model = SVC(
    kernel="rbf",
    random_state=42
)

# Train the model
svm_model.fit(X_train_scaled, y_train)

print("Support Vector Machine model trained successfully.")

Support Vector Machine model trained successfully.


In [16]:
# ==========================================================
# Step 11: SVM Predictions
# ==========================================================

# Generate predictions
y_pred_svm = svm_model.predict(X_test_scaled)

# Display first 10 predictions
print("First 10 Predictions:")
print(y_pred_svm[:10])

First 10 Predictions:
[0 1 1 1 1 0 0 0 0 0]


## Observation

The Support Vector Machine (SVM) model was successfully trained using the scaled training dataset.

Feature scaling was applied because SVM is sensitive to the magnitude of input features. The trained model generated predictions for the testing dataset, which will be evaluated and compared with other machine learning models in the next phase.

In [17]:
# ==========================================================
# Step 12: Train K-Nearest Neighbors (KNN)
# ==========================================================

# Initialize KNN Classifier
knn_model = KNeighborsClassifier(
    n_neighbors=5
)

# Train the model
knn_model.fit(X_train_scaled, y_train)

print("K-Nearest Neighbors model trained successfully.")

K-Nearest Neighbors model trained successfully.


In [18]:
# ==========================================================
# Step 13: KNN Predictions
# ==========================================================

# Generate predictions
y_pred_knn = knn_model.predict(X_test_scaled)

# Display first 10 predictions
print("First 10 Predictions:")
print(y_pred_knn[:10])

First 10 Predictions:
[0 1 1 0 1 0 0 0 0 0]


## Observation

The K-Nearest Neighbors (KNN) model was successfully trained using the scaled training dataset.

Feature scaling was applied because KNN calculates distances between data points, making it sensitive to differences in feature magnitudes. The trained model generated predictions for the testing dataset, which will be evaluated and compared with the other machine learning models in the next phase.

In [19]:
# ==========================================================
# Step 14: Train XGBoost Model
# ==========================================================

# Initialize XGBoost Classifier
xgb_model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=42,
    eval_metric="logloss"
)

# Train the model
xgb_model.fit(X_train, y_train)

print("XGBoost model trained successfully.")

XGBoost model trained successfully.


In [20]:
# ==========================================================
# Step 15: XGBoost Predictions
# ==========================================================

# Generate predictions
y_pred_xgb = xgb_model.predict(X_test)

# Display first 10 predictions
print("First 10 Predictions:")
print(y_pred_xgb[:10])

First 10 Predictions:
[0 1 1 1 1 0 0 0 0 0]


## Observation

The XGBoost model was successfully trained using the unscaled training dataset.

XGBoost is an ensemble boosting algorithm that builds multiple decision trees sequentially, where each new tree attempts to correct the errors of the previous ones. The trained model generated predictions for the testing dataset, which will be evaluated and compared with the other machine learning models in the next phase.

In [21]:
# ==========================================================
# Step 16: Save Trained Machine Learning Models
# ==========================================================

import os
import joblib

# Create models directory if it doesn't exist
os.makedirs("../models", exist_ok=True)

# Save trained models
joblib.dump(lr_model, "../models/logistic_regression.pkl")
joblib.dump(dt_model, "../models/decision_tree.pkl")
joblib.dump(rf_model, "../models/random_forest.pkl")
joblib.dump(svm_model, "../models/svm.pkl")
joblib.dump(knn_model, "../models/knn.pkl")
joblib.dump(xgb_model, "../models/xgboost.pkl")

print("All trained models have been saved successfully.")

All trained models have been saved successfully.


In [22]:
# ==========================================================
# Step 17: Verify Saved Models
# ==========================================================

import os

print("Saved Models:")

for file in os.listdir("../models"):
    print(file)

Saved Models:
xgboost.pkl
svm.pkl
decision_tree.pkl
knn.pkl
.gitkeep
logistic_regression.pkl
random_forest.pkl


# Phase 4 Summary

## Objective Achieved

The objective of this phase was to develop and train multiple supervised machine learning models for predicting cardiovascular disease using the preprocessed clinical health dataset.

All selected machine learning algorithms were successfully trained using the processed training dataset, and prediction results were generated using the testing dataset.

---

## Machine Learning Models Trained

The following models were successfully implemented and trained:

- Logistic Regression
- Decision Tree
- Random Forest
- Support Vector Machine (SVM)
- K-Nearest Neighbors (KNN)
- XGBoost

---

## Tasks Completed

During this phase, the following tasks were completed:

- Imported the required machine learning libraries.
- Loaded the processed training and testing datasets.
- Used scaled datasets for Logistic Regression, Support Vector Machine (SVM), and K-Nearest Neighbors (KNN).
- Used unscaled datasets for Decision Tree, Random Forest, and XGBoost.
- Trained all six machine learning models using the training dataset.
- Generated prediction results for each trained model.
- Saved all trained models in the `models/` directory using the `joblib` library.
- Verified that all trained models were successfully saved for future use.

---

## Output

The following trained machine learning models were generated and stored:

- `logistic_regression.pkl`
- `decision_tree.pkl`
- `random_forest.pkl`
- `svm.pkl`
- `knn.pkl`
- `xgboost.pkl`

These saved models can now be loaded directly without retraining.

---

## Outcome

All machine learning models have been successfully trained and stored for future use. Saving the trained models improves the efficiency, reproducibility, and maintainability of the project.

---

## Next Phase

The next phase will focus on **Model Evaluation and Comparison**.

The saved models will be loaded from the `models/` directory and evaluated using the following performance metrics:

- Accuracy
- Precision
- Recall
- F1-Score
- ROC-AUC Score
- Confusion Matrix

Finally, all models will be compared, and the best-performing model for heart disease prediction will be selected based on their evaluation results.