# Phase 4: Machine Learning Model Development

## Objective

The objective of this phase is to train multiple supervised machine learning models for predicting cardiovascular disease using the preprocessed clinical dataset.

The processed training and testing datasets prepared during the preprocessing phase are used directly to avoid repeating data preparation steps. Each model is trained independently, and prediction results are generated for evaluation in the next phase.

---

## Machine Learning Models

- Logistic Regression
- Decision Tree
- Random Forest
- Support Vector Machine (SVM)
- K-Nearest Neighbors (KNN)
- XGBoost

In [1]:
# ==========================================================
# Step 1: Import Required Libraries
# ==========================================================

import pandas as pd
import numpy as np

# Machine Learning Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

# XGBoost
from xgboost import XGBClassifier

In [7]:
# ==========================================================
# Step 2: Load Processed Datasets
# ==========================================================

# Scaled datasets
X_train_scaled = pd.read_csv("../data/processed/X_train_scaled.csv")
X_test_scaled = pd.read_csv("../data/processed/X_test_scaled.csv")

# Unscaled datasets
X_train = pd.read_csv("../data/processed/X_train.csv")
X_test = pd.read_csv("../data/processed/X_test.csv")

# Target
y_train = pd.read_csv("../data/processed/y_train.csv").squeeze()
y_test = pd.read_csv("../data/processed/y_test.csv").squeeze()

print("All datasets loaded successfully.")

All datasets loaded successfully.


In [8]:
# ==========================================================
# Step 3: Verify Dataset Shapes
# ==========================================================

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("X_train_scaled:", X_train_scaled.shape)
print("X_test_scaled :", X_test_scaled.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (54564, 12)
X_test : (13641, 12)
X_train_scaled: (54564, 12)
X_test_scaled : (13641, 12)
y_train: (54564,)
y_test : (13641,)


## Observation

The processed datasets were successfully loaded and verified.

### Key Findings

- Both scaled and unscaled datasets are available.
- The training and testing datasets contain consistent features.
- The data is ready for machine learning model development.

In [9]:
# ==========================================================
# Step 4: Train Logistic Regression
# ==========================================================

lr_model = LogisticRegression(
    random_state=42,
    max_iter=1000
)

lr_model.fit(X_train_scaled, y_train)

print("Logistic Regression model trained successfully.")

Logistic Regression model trained successfully.


In [10]:
# ==========================================================
# Step 5: Logistic Regression Predictions
# ==========================================================

y_pred_lr = lr_model.predict(X_test_scaled)

print("First 10 Predictions:")
print(y_pred_lr[:10])

First 10 Predictions:
[0 1 1 1 0 0 0 0 0 0]


## Observation

The Logistic Regression model was successfully trained using the scaled training dataset. Predictions were generated for the testing dataset and will be evaluated in the next phase.

In [11]:
# ==========================================================
# Step 6: Train Decision Tree Model
# ==========================================================

# Initialize Decision Tree Classifier
dt_model = DecisionTreeClassifier(
    random_state=42
)

# Train the model
dt_model.fit(X_train, y_train)

print("Decision Tree model trained successfully.")

Decision Tree model trained successfully.


In [12]:
# ==========================================================
# Step 7: Decision Tree Predictions
# ==========================================================

# Generate predictions
y_pred_dt = dt_model.predict(X_test)

# Display first 10 predictions
print("First 10 Predictions:")
print(y_pred_dt[:10])

First 10 Predictions:
[0 1 1 0 1 0 0 1 0 1]


## Observation

The Decision Tree model was successfully trained using the unscaled training dataset.

Prediction results were generated for the testing dataset. These predictions will be evaluated and compared with other machine learning models in the next phase to determine the model's overall performance.

In [13]:
# ==========================================================
# Step 8: Train Random Forest Model
# ==========================================================

# Initialize Random Forest Classifier
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train the model
rf_model.fit(X_train, y_train)

print("Random Forest model trained successfully.")

Random Forest model trained successfully.


In [14]:
# ==========================================================
# Step 9: Random Forest Predictions
# ==========================================================

# Generate predictions
y_pred_rf = rf_model.predict(X_test)

# Display first 10 predictions
print("First 10 Predictions:")
print(y_pred_rf[:10])

First 10 Predictions:
[0 1 1 1 1 0 0 1 0 0]


## Observation

The Random Forest model was successfully trained using the unscaled training dataset.

The model generated predictions for the testing dataset. Random Forest combines multiple decision trees to improve prediction accuracy and reduce overfitting compared to a single Decision Tree. The generated predictions will be evaluated in the next phase.

In [15]:
# ==========================================================
# Step 10: Train Support Vector Machine (SVM)
# ==========================================================

# Initialize SVM Classifier
svm_model = SVC(
    kernel="rbf",
    random_state=42
)

# Train the model
svm_model.fit(X_train_scaled, y_train)

print("Support Vector Machine model trained successfully.")

Support Vector Machine model trained successfully.


In [16]:
# ==========================================================
# Step 11: SVM Predictions
# ==========================================================

# Generate predictions
y_pred_svm = svm_model.predict(X_test_scaled)

# Display first 10 predictions
print("First 10 Predictions:")
print(y_pred_svm[:10])

First 10 Predictions:
[0 1 1 1 1 0 0 0 0 0]


## Observation

The Support Vector Machine (SVM) model was successfully trained using the scaled training dataset.

Feature scaling was applied because SVM is sensitive to the magnitude of input features. The trained model generated predictions for the testing dataset, which will be evaluated and compared with other machine learning models in the next phase.

In [17]:
# ==========================================================
# Step 12: Train K-Nearest Neighbors (KNN)
# ==========================================================

# Initialize KNN Classifier
knn_model = KNeighborsClassifier(
    n_neighbors=5
)

# Train the model
knn_model.fit(X_train_scaled, y_train)

print("K-Nearest Neighbors model trained successfully.")

K-Nearest Neighbors model trained successfully.


In [18]:
# ==========================================================
# Step 13: KNN Predictions
# ==========================================================

# Generate predictions
y_pred_knn = knn_model.predict(X_test_scaled)

# Display first 10 predictions
print("First 10 Predictions:")
print(y_pred_knn[:10])

First 10 Predictions:
[0 1 1 0 1 0 0 0 0 0]


## Observation

The K-Nearest Neighbors (KNN) model was successfully trained using the scaled training dataset.

Feature scaling was applied because KNN calculates distances between data points, making it sensitive to differences in feature magnitudes. The trained model generated predictions for the testing dataset, which will be evaluated and compared with the other machine learning models in the next phase.

In [19]:
# ==========================================================
# Step 14: Train XGBoost Model
# ==========================================================

# Initialize XGBoost Classifier
xgb_model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=42,
    eval_metric="logloss"
)

# Train the model
xgb_model.fit(X_train, y_train)

print("XGBoost model trained successfully.")

XGBoost model trained successfully.


In [20]:
# ==========================================================
# Step 15: XGBoost Predictions
# ==========================================================

# Generate predictions
y_pred_xgb = xgb_model.predict(X_test)

# Display first 10 predictions
print("First 10 Predictions:")
print(y_pred_xgb[:10])

First 10 Predictions:
[0 1 1 1 1 0 0 0 0 0]


## Observation

The XGBoost model was successfully trained using the unscaled training dataset.

XGBoost is an ensemble boosting algorithm that builds multiple decision trees sequentially, where each new tree attempts to correct the errors of the previous ones. The trained model generated predictions for the testing dataset, which will be evaluated and compared with the other machine learning models in the next phase.

# Step 16: Phase 4 Summary

## Objective Achieved

In this phase, multiple supervised machine learning models were successfully trained using the preprocessed clinical health dataset. The processed training and testing datasets created during the preprocessing phase were used to develop predictive models for heart disease classification.

---

## Models Trained

The following machine learning models were successfully implemented:

- Logistic Regression
- Decision Tree
- Random Forest
- Support Vector Machine (SVM)
- K-Nearest Neighbors (KNN)
- XGBoost

---

## Tasks Completed

During this phase, the following tasks were performed:

- Imported all required machine learning libraries.
- Loaded the processed training and testing datasets.
- Used scaled datasets for Logistic Regression, SVM, and KNN.
- Used unscaled datasets for Decision Tree, Random Forest, and XGBoost.
- Trained all six machine learning models using the training dataset.
- Generated predictions for the testing dataset using each trained model.
- Verified that all models were successfully trained without errors.

---

## Outcome

All machine learning models have been successfully developed and trained. Prediction results have been generated for each model and are ready for performance evaluation.

These trained models will be assessed in the next phase using different evaluation metrics to identify the best-performing model for heart disease prediction.

---

## Next Phase

The next phase focuses on **Model Evaluation and Comparison**, where all trained models will be evaluated using various performance metrics, including:

- Accuracy
- Precision
- Recall
- F1-Score
- Confusion Matrix
- ROC Curve
- ROC-AUC Score

A comparative analysis will then be performed to determine the most effective model for predicting cardiovascular disease.